#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Locates a configures a Meross IoT device
"""

import sys

import command_line
import config
import setup
import monitor


if __name__ == "__main__":
    opts, subcommands = command_line.arguments()
    if opts.subcommand is None:
        sys.exit("Missing sub-command, expecting one of:"
                 " {}".format(", ".join(sorted(subcommands.keys()))))
    subcommands[opts.subcommand].go(opts)
